# Generated by Django 5.2.3 on 2025-06-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrOS', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='id_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, to='retrOS.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to='retrOS.user'),
        ),
    ]
