# Generated by Django 5.2.3 on 2025-06-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retrOS', '0003_message_id_read_user_friend_requests_user_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='id_read',
            new_name='is_read',
        ),
    ]
